export const data = {
  activities: [
    {
      ageCategory: 'adult',
      currentParticipants: 1,
      date: '2025-01-01',
      description:
        '## Rafting at the Grand Canyon\r\n Experience the **adrenaline** in this _natural wonder_.',
      id: 1,
      location: 'Grand canyon',
      maxParticipants: 10,
      price: 100,
      slug: 'grand-canyon-rafting',
      status: 'published',
      title: 'Grand canyon rafting',
      userId: 1,
    },
    {
      ageCategory: 'family',
      currentParticipants: 0,
      date: '2025-03-01',
      description:
        '## Explore the Cumbre Vieja **Volcano**\n Experience the **force** of this _natural beast_ on the beautiful island of La Palma',
      id: 2,
      location: 'Cumbre Vieja',
      maxParticipants: 30,
      price: 20,
      slug: 'cumbre-vieja-exploration',
      status: 'published',
      title: 'Cumbre Vieja exploration',
      userId: 1,
    },
    {
      ageCategory: 'adult',
      currentParticipants: 4,
      date: '2024-01-01',
      description:
        '## Hot air Ballon ride over Cappadocia\r\n Experience the **tranquility** in this _natural beauty_.',
      id: 666,
      location: 'Capadoccia',
      maxParticipants: 4,
      price: 200,
      slug: 'balloon-in-cappadocia',
      status: 'cancelled',
      title: 'Balloon in Cappadocia',
      userId: 1,
    },
    {
      ageCategory: 'family',
      currentParticipants: null,
      date: '2023-11-09',
      description:
        'Want you to paddleboard on **Switzerland**?\n With a surface of almost _114 square kilometers_, Lake Lucerne is a popular destination for stand-up paddlers.',
      id: 667,
      location: 'Lucerne',
      maxParticipants: 6,
      price: '50',
      slug: 'stand-up-paddle-surf-in-lake-lucerne',
      status: 'published',
      title: 'Stand-up paddle surf in Lake Lucerne',
      userId: 1,
    },
  ],
  participants: [
    {
      acceptConditions: true,
      activityId: 1,
      address: 'No way 666',
      email: 'jeff@acme.com',
      id: 1,
      name: 'Jeff Gates',
      paymentMethod: 'card',
      phone: '+1 (415) 555-5555',
      userId: 2,
    },
    {
      acceptConditions: true,
      activityId: 667,
      address: 'My home 1',
      email: 'mark@page.me',
      id: 2,
      name: 'Mark Page',
      paymentMethod: 'cash',
      phone: '555123456',
      userId: 3,
    },
  ],
  ageCategories: [
    { id: 'adult', caption: 'Adult', icon: '👨🏼‍🦰' },
    { id: 'child', caption: 'Child', icon: '👦🏼' },
    { id: 'family', caption: 'Family', icon: '👨‍👩‍👧‍👦' },
  ],
  activityStatuses: [
    { id: 'published', caption: 'Published', icon: '📢' },
    { id: 'cancelled', caption: 'Cancelled', icon: '🚫' },
  ],
  paymentMethods: [
    { id: 'cash', caption: 'Cash', icon: '💵' },
    { id: 'card', caption: 'Card', icon: '💳' },
    { id: 'transfer', caption: 'Transfer', icon: '🏦' },
  ],
};
